apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scaleconfigs.py-kube-downscaler.caas-team.github.com
spec:
  scope: Namespaced
  group: py-kube-downscaler.caas-team.github.com
  names:
    kind: ScaleConfig
    plural: scaleconfigs
    singular: scaleconfig
    shortNames:
    - sc
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - targetRef
            - scaleRule
            properties:
              targetRef:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - kind
                - name
              scaleRule:
                type: object
                properties:
                  name:
                    type: string
                  schedule:
                    type: string
                required:
                - name
                - schedule
